        SUBROUTINE INTIME(HOURS, MINUTES, SECONDS)
	IMPLICIT INTEGER (A-Z)
        DIMENSION TARRAY(3)
C	CALL GETTIM(HOURS, MINUTES, SECONDS, HUNDREDTHS)
        CALL ITIME(TARRAY)
        HOURS = TARRAY(1)
        MINUTES = TARRAY(2)
        SECONDS = TARRAY(3)
	END

	SUBROUTINE INIRND(SEED)
	INTEGER SEED,SEEDY
	COMMON /RANDOM/ SEEDY
	SEEDY = SEED
	END

	FUNCTION RND(MAXVAL)
	IMPLICIT INTEGER (A-Z)
	COMMON /RANDOM/ SEEDY
	SEEDY = IAND(SEEDY*(1024+32+2+1) + 17, '7FFFFFFF'X)
	RND = MOD((SEEDY/100),MAXVAL)
	END

	SUBROUTINE EXIT
C NO "CALL EXIT" HERE
	STOP
	END

